services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda

    command:
      - redpanda
      - start
      - --smp=1
      - --overprovisioned
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092

    ports:
      - "9092:9092"



  postgres-primary:
    image: postgres:16
    container_name: postgres-primary
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:-urlshortener}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD:?Set REPLICATION_PASSWORD in .env}
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=5
      -c hot_standby=on
      -c hba_file=/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./docker/primary-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d urlshortener"]
      interval: 5s
      timeout: 3s
      retries: 12

  postgres-replica:
    image: postgres:16
    container_name: postgres-replica
    environment:
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD:?Set REPLICATION_PASSWORD in .env}
    ports:
      - "5433:5432"
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./docker/replica-init:/bootstrap:ro
    command: ["bash", "/bootstrap/replica-init.sh"]
    depends_on:
      postgres-primary:
        condition: service_healthy

volumes:
  primary_data:
  replica_data: