#!/bin/bash
set -e

: "${REPLICATION_PASSWORD:?REPLICATION_PASSWORD must be set}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE ROLE replicator WITH LOGIN REPLICATION PASSWORD '$REPLICATION_PASSWORD';
EOSQL
